name: build_upload

on:
  push:
    branches:
      - feature/CI_CD

jobs:
  build_upload:
    name: Build and Upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - core
          - fleetcarpooling
          - manuallyaddition
          - qraddition

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Get Branch Name
        id: branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF##/})"
      - name: Get Today Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      - name: Get Folder ID by condition
        uses: haya14busa/action-cond@v1
        id: folder_Id
        with:
          cond: ${{ steps.branch.outputs.branch == 'feature/CI_CD' }}
          if_true: ${{secrets.DRIOD_FOLDER_ID}}

      - name: Flutter Pub Get for All Projects
        run: |
          for project in ${{ matrix.project }}; do
            cd $project
            flutter pub get
            cd ..
          done

      - name: Print Current Directory
        run: pwd

      - name: Move to Fleetcarpooling Directory
        run: cd fleetcarpooling

      - name: Print Current Directory
        run: pwd

      - name: Print files from Directory
        run: ls

      - name: Move to Fleetcarpooling Directory
        run: cd fleetcarpooling

      - name: Print Current Directory
        run: pwd

      - name: Print files from Directory
        run: ls

      - name: Flutter Build APK --Release for Fleetcarpooling
        run: flutter build apk --release
